formtest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('testapp.urls', namespace='testapp')),
    path('likelion/', include('likelion.urls', namespace='likelion')),
]

likelion/urls.py
app_name = 'likelion'

testapp/urls.py
from django.urls import path
from .views import PostCreateView, PostDetailView, PostListView

app_name = 'testapp'

urlpatterns = [
    path('list/', PostListView.as_view(), name='post_list'),
    path('list/<int:pk>', PostDetailView.as_view(), name='post_detail'),
    path('create/', PostCreateView.as_view(), name='post_create'),
]

likelion/models.py
from django.db import models

# Create your models here.

testapp/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=250)
    USER_MAN, USER_WOMAN = 'M', 'N'
    USER_TYPE = (
        (USER_MAN, '남성'),
        (USER_WOMAN, '여성'),
    )
    sex = models.CharField(max_length=1, choices=USER_TYPE)

testapp/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'sex',
        )
        widgets = {
            'sex': forms.ChoiceField(choices=Post.USER_TYPE)
        }

likelion/views.py
from django.shortcuts import render

# Create your views here.

testapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView
from .forms import PostCreateForm
from .models import Post


class PostListView(ListView):
    template_name = 'testapp/post_list.html'
    model = Post


class PostDetailView(DetailView):
    template_name = 'testapp/post_detail.html'
    model = Post


class PostCreateView(CreateView):
    template_name = 'testapp/post_create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('testapp:post_list')

likelion/templates/study.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="function.js"></script>
    <title>Document</title>
</head>
<body>
<li>this is basic webpage</li>

<h1><script>
    whichOne(A,B)
</script></h1>
<br>
ahahahaha

</body>
</html>

testapp/templates/testapp/post_create.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form method="post">
     {{ form.as_p }}
    <button type="submit">제출</button>
</form>

</body>
</html>

testapp/templates/testapp/post_detail.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {{ post.title }}
    <br>
{{ post.sex }}

</body>
</html>

testapp/templates/testapp/post_list.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<a href="{% url 'testapp:post_create' %}">만들기</a>
{% for post in object_list %}
    <li><a href="{% url 'testapp:post_detail' post.id %}">{{ post }}</a></li>
{% endfor %}

</body>
</html>